// C++ excerpts preserved from Aaron's portfolio draft.
export const HMI_CODE = {
  split:
    "void DwindleTree::add(QWidget* w, QWidget* split_target) {\n    auto* newLeaf = makeLeaf(w);\n    if (!root_) { root_ = newLeaf; return; }\n\n    DwindleNode* target = split_target ? leafFor(split_target) : nullptr;\n    if (!target) {                       // fallback: leftmost leaf\n        target = root_;\n        while (target->isNode && target->children[0]) target = target->children[0];\n    }\n\n    // Replace target with an internal node holding {target, newLeaf}.\n    auto* newParent = new DwindleNode();\n    newParent->isNode = true;\n    newParent->parent = target->parent;\n    // Smart split: taller box → top/bottom, wider box → left/right\n    newParent->splitTop = (target->box.height() >= target->box.width());\n\n    if (target->parent) {\n        if (target->parent->children[0] == target) target->parent->children[0] = newParent;\n        else                                       target->parent->children[1] = newParent;\n    } else {\n        root_ = newParent;\n    }\n\n    target->parent  = newParent;\n    newLeaf->parent = newParent;\n    newParent->children[0] = target;\n    newParent->children[1] = newLeaf;\n    all_nodes_.push_back(newParent);\n}",
  geometry:
    "void DwindleTree::recalcNode(DwindleNode* n, int gap) {\n    if (!n->isNode) {\n        if (n->widget) n->widget->setGeometry(n->box.adjusted(gap, gap, -gap, -gap));\n        return;\n    }\n    auto* c0 = n->children[0];\n    auto* c1 = n->children[1];\n    if (!c0 || !c1) return;\n\n    if (!n->splitTop) {\n        int w0 = (int)(n->box.width() / 2.0f * n->splitRatio);\n        // max(min()) not std::clamp: bounds may cross when box < 2*min_pane\n        w0 = std::max(min_pane_w_, std::min(w0, n->box.width() - min_pane_w_));\n        c0->box = QRect(n->box.x(), n->box.y(), w0, n->box.height());\n        c1->box = QRect(n->box.x() + w0, n->box.y(), n->box.width() - w0, n->box.height());\n    } else {\n        int h0 = (int)(n->box.height() / 2.0f * n->splitRatio);\n        h0 = std::max(min_pane_h_, std::min(h0, n->box.height() - min_pane_h_));\n        c0->box = QRect(n->box.x(), n->box.y(), n->box.width(), h0);\n        c1->box = QRect(n->box.x(), n->box.y() + h0, n->box.width(), n->box.height() - h0);\n    }\n    recalcNode(c0, gap);\n    recalcNode(c1, gap);\n}",
  collapse:
    "auto* parent  = leaf->parent;\nauto* sibling = leaf->sibling();\n\nsibling->parent = parent->parent;          // sibling takes parent's place\nif (parent->parent) {\n    if (parent->parent->children[0] == parent) parent->parent->children[0] = sibling;\n    else                                       parent->parent->children[1] = sibling;\n} else {\n    root_ = sibling;\n}\ndelete leaf;\ndelete parent;",
};
